import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser, hasActiveSub } from "@/lib/auth";
import type { DeepScanResult } from "@/lib/deep-scanner";

function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function generateReportHtml(data: DeepScanResult, whiteLabel: boolean): string {
  const scoreColor = data.overallScore >= 75 ? "#16a34a" : data.overallScore >= 45 ? "#ca8a04" : "#dc2626";

  const actionRows = data.actionPlan.map((a, i) => {
    const impactColor = a.impact === "high" ? "#dc2626" : a.impact === "medium" ? "#ca8a04" : "#6b7280";
    const codeBlock = a.code
      ? `<pre style="background:#f3f4f6;padding:12px;border-radius:6px;font-size:11px;overflow-x:auto;margin-top:8px;border:1px solid #e5e7eb">${escapeHtml(a.code)}</pre>`
      : "";
    return `
      <tr style="border-bottom:1px solid #e5e7eb">
        <td style="padding:12px 8px;font-size:13px;vertical-align:top;width:30px;color:#9ca3af">${i + 1}</td>
        <td style="padding:12px 8px;font-size:13px;vertical-align:top">
          <span style="color:${impactColor};font-weight:600;font-size:11px;text-transform:uppercase">${a.impact} impact</span>
          <span style="color:#6b7280;font-size:11px"> &middot; ~${a.estimatedPoints} pts &middot; ${escapeHtml(a.category)}</span>
          <br/><span style="color:#111">${escapeHtml(a.fix)}</span>
          ${codeBlock}
        </td>
      </tr>`;
  }).join("");

  const pageRows = data.pages.map((p) => `
    <tr style="border-bottom:1px solid #e5e7eb">
      <td style="padding:8px;font-size:12px;color:#111">${escapeHtml(p.url)}</td>
      <td style="padding:8px;font-size:12px;color:#6b7280">${p.type}</td>
      <td style="padding:8px;font-size:14px;font-weight:700;color:${p.result.overallScore >= 75 ? "#16a34a" : p.result.overallScore >= 45 ? "#ca8a04" : "#dc2626"}">${p.result.overallScore}</td>
    </tr>
  `).join("");

  const catRows = data.aggregatedCategories.map((c) => {
    const pct = c.maxScore > 0 ? Math.round((c.score / c.maxScore) * 100) : 0;
    const color = pct >= 70 ? "#16a34a" : pct >= 40 ? "#ca8a04" : "#dc2626";
    return `
      <tr style="border-bottom:1px solid #e5e7eb">
        <td style="padding:8px;font-size:13px">${escapeHtml(c.name)}</td>
        <td style="padding:8px;font-size:13px;font-weight:600;color:${color}">${c.score}/${c.maxScore}</td>
        <td style="padding:8px;font-size:13px;color:${color}">${pct}%</td>
      </tr>`;
  }).join("");

  const branding = whiteLabel ? "" : `
    <div style="text-align:center;padding:20px;color:#9ca3af;font-size:11px;border-top:1px solid #e5e7eb;margin-top:40px">
      Generated by AgentReady &middot; agentready.dev
    </div>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Agent Readiness Report - ${escapeHtml(data.rootUrl)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 24px; color: #111; }
  table { width: 100%; border-collapse: collapse; }
  h2 { font-size: 16px; margin: 32px 0 12px; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
  @media print { body { padding: 0; } }
</style></head>
<body>
  <div style="margin-bottom:32px">
    <h1 style="font-size:24px;margin:0 0 4px">Agent Readiness Report</h1>
    <p style="color:#6b7280;font-size:14px;margin:0">${escapeHtml(data.rootUrl)} &middot; ${new Date(data.scannedAt).toLocaleDateString()}</p>
  </div>

  <div style="display:flex;gap:24px;margin-bottom:32px;align-items:center">
    <div style="text-align:center">
      <div style="font-size:48px;font-weight:800;color:${scoreColor}">${data.overallScore}</div>
      <div style="font-size:14px;color:#6b7280">${data.grade}</div>
    </div>
    <div style="font-size:13px;color:#6b7280">
      <p style="margin:4px 0">Platform: <strong style="color:#111">${data.platform}</strong></p>
      <p style="margin:4px 0">Pages scanned: <strong style="color:#111">${data.totalPages}</strong></p>
      <p style="margin:4px 0">Issues found: <strong style="color:#111">${data.actionPlan.length}</strong></p>
      <p style="margin:4px 0">Scan time: <strong style="color:#111">${data.scanDurationMs}ms</strong></p>
    </div>
  </div>

  <h2>Category Scores</h2>
  <table>${catRows}</table>

  <h2>Pages Scanned</h2>
  <table>${pageRows}</table>

  <h2>Action Plan (${data.actionPlan.length} fixes, sorted by impact)</h2>
  <table>${actionRows}</table>

  ${branding}
</body></html>`;
}

export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Sign in first." }, { status: 401 });
  if (!hasActiveSub(user)) return NextResponse.json({ error: "Active subscription required." }, { status: 403 });

  const { scanData, whiteLabel } = await req.json();
  if (!scanData) return NextResponse.json({ error: "Scan data required." }, { status: 400 });

  const isAgency = user.plan === "agency";
  const html = generateReportHtml(scanData as DeepScanResult, whiteLabel && isAgency);

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="agentready-report-${Date.now()}.html"`,
    },
  });
}
